### ISSUE TITLE
How to set working directory for unittest in neotest setup?

### ISSUE THREAD

**Issue by akvilary** [nvim-neotest/neotest-python#19]
Case: I have tests in repo, but iI need to run it in different directory.
It seems as cwd in adapter setup does not work. I also have tried to put cwd to adapters = dap = {cwd = 'path_here'} (it is also not worked)
```
local neotest = require("neotest")
neotest.setup({
  adapters = {
    require("neotest-python")({
        python = "/opt/python3.7/bin/python3.7",
        runner = "unittest",
        cwd = '/tmp/tests/mega_project/tests/stateless/run',
    })
  },
})

local envs = {}
envs['LD_LIBRARY_PATH'] = '.'
envs['PYTHONPATH'] = '$PYTHONPATH:/home/user/repos/some_project'

local run_test = function()
    require("neotest").run.run({
        strategy = "dap",
        env = envs
    })
end

vim.keymap.set('n', '<F4>', run_test)
```

**Comment by rcarriga** [comment]
There is no `cwd` setting for neotest-python, it's agnostic to the project location. All paths are passed in from the core plugin.

You can pass `cwd` to the `run` function: `require("neotest").run.run({ cwd = ... })`

**Comment by rbhanot4739** [comment]
@rcarriga The `cwd` option to `require("neotest").run.run()` no longer seems work ! Let's say I am inside some deeply nested sub-directory inside my project root, the `require("neotest").run.run({ cwd = ... })` didn't work for me. For example if I have the following directory structure
```
project/
├── project-code/
│  ├── src/
│  ├── test/
│  └── pyproject.toml
└── config/

```
So, here the root detected by the lsp is `project` (due to `pyproject.toml` file inside it) which has the `test` directory. So when I run `require("neotest").run.run(vim.uv.cwd())` from inside the `project-code` directory all tests are detected and run, however if I go one directory up(i.e. inside the main `project` directory) and try to do `require("neotest").run.run({cwd = vim.uv.cwd() .. "project-code")` , I get `No tests found`. I even tried providing the hard-coded path but even that didn't work. 

I was also looking another thread where you mentioned passing `suite = true` when you are not in the directory that contains tests, so I ran `require("neotest").run.run({suite = true})` but I got the following errors

```
E5108: Error executing lua ...bhanot/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:100: Async task failed without callback: The coroutine failed with this message: 
...ocal/share/nvim/lazy/neotest/lua/neotest/client/init.lua:337: assertion failed!
stack traceback:
	[C]: in function 'assert'
	...ocal/share/nvim/lazy/neotest/lua/neotest/client/init.lua:337: in function '_get_adapter'
	...ocal/share/nvim/lazy/neotest/lua/neotest/client/init.lua:203: in function <...ocal/share/nvim/lazy/neotest/lua/neotest/client/init.lua:197>
	...al/share/nvim/lazy/neotest/lua/neotest/consumers/run.lua:39: in function 'get_tree_from_args'
	...al/share/nvim/lazy/neotest/lua/neotest/consumers/run.lua:80: in function 'func'
	...bhanot/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:173: in function <...bhanot/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:172>
stack traceback:
	[C]: in function 'error'
	...bhanot/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:100: in function 'close_task'
	...bhanot/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:122: in function 'step'
	...bhanot/.local/share/nvim/lazy/nvim-nio/lua/nio/tasks.lua:150: in function 'run'
	[string ":lua"]:1: in main chunk
```
This is how my config looks like

```
 {
  "nvim-neotest/neotest",
  optional = true,
  dependencies = {
    -- "nvim-neotest/neotest-python",
    "nvim-neotest/nvim-nio",
    "nvim-lua/plenary.nvim",
    "antoinemadec/FixCursorHold.nvim",
    "nvim-treesitter/nvim-treesitter",
  },
  keys = {
    {
      "<leader>tT",
      function()
        require("neotest").run.run(LazyVim.root())
      end,
      desc = "Run All Test Files",
    },
  },

  opts = {
    adapters = {
      ["neotest-python"] = {
        dap = { justMyCode = true },
        pytest_discover_instances = true,
      },
    },
  },
}

```

Am I doing something incorrect here ?
