### ISSUE TITLE
No tests found if running from a non-test file

### ISSUE THREAD

**Issue by filipgodlewski** [nvim-neotest/neotest-python#40]
Hey, I know this might be self explanatory, but hear me out ;)

So let's say I have the following folder structure:

```
test_py
├── main.py
├── test_bar.py
└── test_foo.py
```

If I open either `test_foo.py` or `test_bar.py` and run `:lua require'neotest'.summary.toggle()`, it will successfully parse all tests (including the other not-opened-yet test files). I can then run the tests from the summary, all is totally fine.

The problem:
If I try to do the same from `main.py` (let's say that I don't have other buffers open yet), it will parse the tests forever ('Parsing tests'). If I close and reopen the summary, it will finally tell me that it could not find any tests. All is fixed again, if I open any test file, but as you can imagine, it is far from optimal :(

The question is, is it a bug, is it an enhancement request, or can it be solved with a better `.is_test_file()`?

**Comment by rcarriga** [comment]
It sounds like a project root is not being found and thus parsing isn't started until a test buffer is opened, which would be expected behaviour. The adapter looks for certain files to determine the project root (can be found here https://github.com/rcarriga/neotest-python/blob/52624d1306cb2b401aa72c1d0bee90438916ba7d/lua/neotest-python/init.lua#L72).

The summary not updating to say `No tests found` is odd though, could you enable info logs (pass `log_level = vim.log.levels.INFO,` to the setup config) and paste the log here after reproducing?

**Comment by filipgodlewski** [comment]
I will test it in about 3h, but an idea came to me that maybe the reason was because there was no `.git/` root folder. This was actually a one-off test dir (not a repo), and so I'll give it a try and will let you know

**Comment by filipgodlewski** [comment]
Or maybe that's not the log that I was supposed to paste :P Sorry, but I could not find info on where is the vim.log stored, if it is different from the runtime log

**Comment by filipgodlewski** [comment]
Great, thanks, will bear that in mind
